apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foo-tenant
  namespace: argo-cd
spec:
  destinations:
    - namespace: foo-dest
      server: "https://kubernetes.default.svc"
  sourceNamespaces:
    - foo
